name: assimp

on:
  push:
    paths:
      - .github/workflows/assimp.yml
      - assimp/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: assimp, version: v0.12.6 }
    secrets: inherit
