name: assimp

on:
  push:
    paths:
      - assimp/**
      - .github/workflows/assimp.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: assimp, version: v0.12.4 }
    secrets: inherit
