name: blend2d

on:
  push:
    paths:
      - blend2d/**
      - .github/workflows/blend2d.yml

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: { lib: blend2d, version: add }
    secrets: inherit
