name: fmt

on:
  push:
    paths:
      - .github/workflows/fmt.yml
      - fmt/**

jobs:
  ci:
    permissions:
      contents: write
    uses: ./.github/workflows/_build.yml
    with: { lib: fmt, version: v1.0 }
    secrets: inherit
