name: freetype

on:
  push:
    paths:
      - .github/workflows/freetype.yml
      - freetype/**

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: { lib: freetype, version: v1.0 }
    secrets: inherit
