name: freetype

on:
  push:
    paths:
      - .github/workflows/freetype.yml
      - freetype/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: freetype, version: v0.12.5 }
    secrets: inherit
