name: glew

on:
  push:
    paths:
      - glew/**
      - .github/workflows/glew.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    # uses: ./.github/workflows/_buildnoemscripten.yml
    with: {
        lib: glew,
        version: v0.12.6,
        # multistrap: true,
        linux_apt: libx11-dev libglu1-mesa-dev libgl1-mesa-dev
          libwayland-dev libxkbcommon-dev xorg-dev libegl1-mesa-dev
          libopengl-dev libglx-dev libglvnd-dev,
      }
    secrets: inherit
