name: json

on:
  push:
    paths:
      - json/**
      - .github/workflows/json.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: json, version: v0.12.5 }
    secrets: inherit
