name: json

on:
  push:
    paths:
      - .github/workflows/json.yml
      - json/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: json, version: v1.0 }
    secrets: inherit
