name: kissfft

on:
  push:
    tags:
      - "v*"
    paths:
      - kissfft/**
      - .github/workflows/kissfft.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: kissfft, version: v0.12.4 }
    secrets: inherit
