name: kissfft

on:
  push:
    paths:
      - .github/workflows/kissfft.yml
      - kissfft/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: kissfft, version: v0.12.5 }
    secrets: inherit
