name: mango

on:
  push:
    paths:
      - mango/**
      - .github/workflows/mango.yml

jobs:
  ci:
    permissions:
      contents: write
    uses: ./.github/workflows/_build.yml
    with: { lib: mango, version: v1.0, meson: true }
    secrets: inherit
