name: mango

on:
  push:
    paths:
      - mango/**
      - .github/workflows/mango.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: mango, version: v0.12.6, meson: true }
    secrets: inherit
