name: OpenImageIO

on:
  push:
    paths:
      - .github/workflows/OpenImageIO.yml
      - OpenImageIO/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: OpenImageIO, version: add, brew: libtiff }
    secrets: inherit
