name: opencv

on:
  push:
    paths:
      - .github/workflows/opencv.yml
      - opencv/**

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: { lib: opencv, version: v1.0 }
    secrets: inherit
