name: opencv

on:
  push:
    paths:
      - .github/workflows/opencv.yml
      - opencv/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: opencv, version: v0.12.6 }
    secrets: inherit
