name: OpenImageIO

on:
  push:
    paths:
      - OpenImageIO/**
      - .github/workflows/OpenImageIO.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: OpenImageIO, version: add, brew: libtiff }
    secrets: inherit
