name: pffft

on:
  push:
    paths:
      - .github/workflows/pffft.yml
      - pffft/**

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    # with: { lib: pffft, version: v1.0 }
    with: { lib: pffft, version: add }
    secrets: inherit
