name: pixman

on:
  push:
    paths:
      - .github/workflows/pixman.yml
      - pixman/**

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: { lib: pixman, version: v1.0, meson: true }
    secrets: inherit
