name: pixman

on:
  push:
    paths:
      - .github/workflows/pixman.yml
      - pixman/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: pixman, version: v0.12.6, meson: true }
    secrets: inherit
