name: poco

on:
  push:
    paths:
      - poco/**
      - .github/workflows/poco.yml

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: { lib: poco, version: add, linux_apt: libssl-dev }
    secrets: inherit
