name: uriparser

on:
  push:
    paths:
      - .github/workflows/uriparser.yml
      - uriparser/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: uriparser, version: v0.12.5 }
    secrets: inherit
