name: uriparser

on:
  push:
    tags:
      - "v*"
    paths:
      - uriparser/**
      - .github/workflows/uriparser.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: uriparser, version: v0.12.4 }
    secrets: inherit
