name: uriparser

on:
  push:
    paths:
      - .github/workflows/uriparser.yml
      - uriparser/**

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: { lib: uriparser, version: v1.0 }
    secrets: inherit
