name: utfcpp

on:
  push:
    tags:
      - "v*"
    paths:
      - utfcpp/**
      - .github/workflows/utfcpp.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: utfcpp, version: v0.12.4 }
    secrets: inherit
