name: utfcpp

on:
  push:
    paths:
      - .github/workflows/utfcpp.yml
      - utfcpp/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: utfcpp, version: v1.0 }
    secrets: inherit
