name: yaml-cpp
# 001

on:
  push:
    paths:
      - .github/workflows/yaml-cpp.yml
      - yaml-cpp/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: yaml-cpp, version: v0.12.5 }
    secrets: inherit
