name: zlib-ng

on:
  push:
    tags:
      - "v*"
    paths:
      - zlib-ng/**
      - .github/workflows/zlib-ng.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: zlib-ng, version: v0.12.4 }
    secrets: inherit
