name: zlib-ng

on:
  push:
    paths:
      - .github/workflows/zlib-ng.yml
      - zlib-ng/**

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: zlib-ng, version: v0.12.5 }
    secrets: inherit
