name: zlib-ng

on:
  push:
    paths:
      - .github/workflows/zlib-ng.yml
      - zlib-ng/**

jobs:
  ci:
    permissions:
      contents: write

    uses: ./.github/workflows/_build.yml
    with: { lib: zlib-ng, version: v1.0 }
    secrets: inherit
