name: zstd

on:
  push:
    paths:
      - zstd/**
      - .github/workflows/zstd.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: zstd, version: v0.12.5, meson: true }
    # passes GITHUB_TOKEN automatically
    secrets: inherit
